### ISSUE TITLE
Create graphics for 2020 strategy

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/strategy#83]
[Design brief](https://docs.google.com/document/d/1UGJzi-u0suzPcI3S12UmgFhgWiOtRt-lkebTqpe2etk/edit)

**Comment by flukeout** [comment]
**Questions**
- Will the slide deck where these are originally from live on into the future?
  - If so, this affects our design choices a little bit as we'll want the diagrams to work on both the website and deck.

**Comment by KevZawacki** [comment]
Thanks @flukeout. cc @samanthaburton, who can speak to the deck's lifespan.

**Comment by samanthaburton** [comment]
The plan is to make a new (version of the) deck, to reflect the updated
strategy and including revised graphics.

On Tuesday, 28 June 2016, Kevin Zawacki notifications@github.com wrote:

> Thanks @flukeout https://github.com/flukeout. cc @samanthaburton
> https://github.com/samanthaburton, who can speak to the deck's
> lifespan.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/strategy/issues/83#issuecomment-229131379,
> or mute the thread
> https://github.com/notifications/unsubscribe/AP72rcvcdKEcjOUDXu4vNg0agulv7azTks5qQWGpgaJpZM4I-Az_
> .

## 

Sam Burton
Lead, Issues, Insights & Impact | Mozilla Foundation

_Cell: *+1 416.877.0710 | *Twitter:_ @TheSamBurton
http://twitter.com/thesamburton\* | Skype:\* samantha.v.burton
Currently in Toronto

**Comment by xmatthewx** [comment]
Hi @samanthaburton – Given the upcoming holiday(s) and PTO, there are just a few days to execute the design before we review them (Friday?), hand them over (Tue?) for implementation (Wed?), in advance on the Board meeting (Friday). 

It's enough time to clean up the lines, colors, and typography, but it's not enough time to properly investigate what the diagrams communicate and how they do it. That would require a bit more time. 

Glad to proceed if that works for you and Mark, but just wanted to make sure we set clear expectations.

**Comment by xmatthewx** [comment]
@samanthaburton – do you anticipate a need to edit this later? often? if not...

@flukeout – since these will likely appear in multiple places, we'll probably want to shift to a white background and more sophisticated colors, line weight, type. They can be inserted in the deck as images, rather than editable elements.

**Comment by samanthaburton** [comment]
That sounds fine Matthew, thanks to you and your team for pushing on such a
tight timeline.

The only one I'm worried might not make sense with just the text changed is
the first graphic, which illustrates all the elements of our strategy -
that one may need a bit more work than the others.

Goal is for these not to change very often or much, if at all, from this
point on.

On Tuesday, 28 June 2016, matthew w notifications@github.com wrote:

> @samanthaburton https://github.com/samanthaburton – do you anticipate a
> need to edit this later? often? if not...
> 
> @flukeout https://github.com/flukeout – since these will likely appear
> in multiple places, we'll probably want to shift to a white background and
> more sophisticated colors, line weight, type. They can be inserted in the
> deck as images, rather than editable elements.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/strategy/issues/83#issuecomment-229146521,
> or mute the thread
> https://github.com/notifications/unsubscribe/AP72rRpoja70lvxt8MPsSLoT9YFtKf3Jks5qQW15gaJpZM4I-Az_
> .

## 

Sam Burton
Lead, Issues, Insights & Impact | Mozilla Foundation

_Cell: *+1 416.877.0710 | *Twitter:_ @TheSamBurton
http://twitter.com/thesamburton\* | Skype:\* samantha.v.burton
Currently in Toronto

**Comment by KevZawacki** [comment]
@samanthaburton Thanks for the clarity!

**Comment by flukeout** [comment]
@KevZawacki @samanthaburton Do either of you have a link to the google presentation where the original diagrams live? I can't find it.

**Comment by xmatthewx** [comment]
Found via Luke and Jordan: https://docs.google.com/presentation/d/10zxivKN4Y4vgvlQZRbVVYynZqrFV-KOpvWEjpPM_8Ps/edit#slide=id.g1521a4b809_2_14

**Comment by flukeout** [comment]
Here's a crack at converting the first diagram.

![image](https://cloud.githubusercontent.com/assets/25212/16463759/10164fb4-3dec-11e6-8404-fbc3ea34e14d.png)

Original for reference...

https://github.com/MozillaFoundation/strategy/issues/83#issuecomment-229445674

**Issues**
- Sandstone is quite narrow (540px), which will require reworking a lot of the diagrams to fit.
  - This makes it harder to re-use these diagrams in a presentation format down the road.
- This diagram is very text heavy, seems like it might be better to write some content about this stuff instead of locking it into an image where it can't be copy and pasted or indexed for searches. 

**Questions**
- Is this roughly what you're looking for?
- Specifically, I'd like some feedback on the general presentation of the diagram as I need settle on a style quickly in order to get through the rest of them in time. I'll ping the design team too.

cc @KevZawacki @samanthaburton

**Comment by flukeout** [comment]
Feedback from @sabrinang 

> Maybe you can simplify it even more by removing the line - is it trying to express a timeline or sum of actions for the result? The A B C is a bit faint on the diagram. The style of the diagram feels pretty different from the sandstone website... if it is for informational, evergreen purposes you can make it more generic to match (fira sans to open sans and purple to grey). For audiences who aren't familiar with unified mofo style that diagram would feel out of place a bit

**Comment by flukeout** [comment]
As discussed with @xmatthewx, I'll convert one more diagram into this format and await feedback, further direction.

**Comment by KevZawacki** [comment]
@flukeout These look fantastic! 

cc @xmatthewx 

A development in this ever-complicated saga: The devs now note that they don't have the bandwidth to create the three subpages on mozilla.org/foundation before July 7, where these excellent designs will live. 

I've asked Mark for an update, asap, re: if/where these designs will now live for the July 7 meeting. I will let you know as soon as I hear back. Mark may still want them before deadline, or might suggest we hit pause.

Really sorry for the confusion here -- this is messy and not an optimal situation at all. Thank you for your patience.

**Comment by flukeout** [comment]
Okay - I'll stay tuned. In the meantime, here are the pyramids reworked...

![image](https://cloud.githubusercontent.com/assets/25212/16467277/838b4404-3dfb-11e6-960c-cdd260c5f5fc.png)

**Comment by KevZawacki** [comment]
Thanks, @flukeout. Pyramid design looks excellent!

**Comment by Lottarao** [comment]
Yes, truly does. Thank you!

**Comment by KevZawacki** [comment]
@xmatthewx @flukeout

From Mark:

"My sense is it's worth getting the new graphics done ASAP and including them in whatever version of the strategy we're linking to."

We're linking to the wiki, so we can add the graphics there.

Thanks again!

**Comment by flukeout** [comment]
Okay, I'll continue on then. So these will live on a wiki now instead of in the Sandstone page? Can I have a link to see how the wiki presence looks like?

**Comment by KevZawacki** [comment]
@flukeout They will live on a wiki temporarily, but ultimately and permanently (and soon) live on a Sandstone page. 

Here's the [wiki](https://wiki.mozilla.org/MoFo_2020) -- but I definitely don't think we need to design for it.

**Comment by flukeout** [comment]
MLN & Advocacy

![image](https://cloud.githubusercontent.com/assets/25212/16472237/79184c6c-3e17-11e6-91a0-0d83f9df44a7.png)

**Comment by flukeout** [comment]
Audience...

![image](https://cloud.githubusercontent.com/assets/25212/16472324/0ce8b026-3e18-11e6-93bc-f05b1c554c20.png)

**Comment by flukeout** [comment]
I'm going to let these sit here for a bit and return to them tomorrow. In the meantime, please let me know if you want any changes or have suggestions.

**Comment by ldecoursy** [comment]
These are looking clean and consistent 😃 

For MLN, I think a representation of [this image](https://docs.google.com/presentation/d/12H3lR_9aW-28YXQbfANSvj37l-xfJVZ7D5imV-qr7UE/edit#slide=id.g114a308848_2_45) (slide 9) may be more useful as it illustrates how the key initiatives thread/connect the hubs. 

Also, for the audiences, the current layout makes it hard to distinguish them as tiers.

**Comment by KevZawacki** [comment]
@flukeout 👍 I think these are spot-on

**Comment by flukeout** [comment]
Thanks for the feedback @ldecoursy. I'm taking diagrams from an existing document and that one you linked isn't included, but - we certainly could. What do you think @KevZawacki ?

**Comment by KevZawacki** [comment]
@flukeout I'm just a proxy for Sam B. at the moment -- so can only communicate that she requested specific diagrams be souped-up. We should probably stick to Sam's request until/unless she says otherwise.

**Comment by flukeout** [comment]
Sounds good @KevZawacki

**Comment by flukeout** [comment]
Update to the Audience diagram...

![image](https://cloud.githubusercontent.com/assets/25212/16496646/d0ae93ba-3ea7-11e6-87a9-7b46bb4ee2f8.png)

**Comment by flukeout** [comment]
Okay here is the latest version of each diagram...

* [Dark days of the internet](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_dark-days.png)
* [MLN audiences](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mln-audiences.png)
* [MLN structure](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mln.png)
* [Mozilla Advocacy Engine](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mozilla-advocacy-engine.png)
* [Scale to Depth](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_scale-to-depth.png)

**Comment by KevZawacki** [comment]
These look awesome, @flukeout. Thanks again. 😁 

A handful of very small edits:

First link: Change "Dark days **of** the internet" to "Dark days **for** the internet"

Third link: Change "**fellowhips**" to "**fellowships**" // Change "web **sits**" to "web **sites**"

Fourth link: Capitalize "**Mozilla**" beneath "field"

Fifth link: Remove extra "**a**" in "**teaach-ins**"

@samanthaburton will be back on Monday and can weigh in, too.

**Comment by flukeout** [comment]
Making the changes now and will await further requests from @samanthaburton 

**Edit** - updates are made.

**Comment by samanthaburton** [comment]
These look great @flukeout! I haven't had a chance to look in-depth at all the text yet, and will do so in a moment. But one quick important change for the first link (Dark days for the Internet) - intent was to change the text in this diagram, as well as restructure it. Apologies that this wasn't clear initially!

On [pg. 2 of the strategy](https://docs.google.com/document/d/1KLFDzyr1jC-19TH7sI6WEBSYmo2KUyzxHzgb0j_KaUg/edit), in the table above the old diagram you'll see the new text and reworked structure (what - why - how x2). The text in that table and the paragraphs above it should be what populates the diagram in the first link. 

Does that make sense? Let me know if you have questions, also happy to jump on a call if that's helpful. Thanks so much!!

**Comment by flukeout** [comment]
Oh dang, totally missed that @samanthaburton - so the updated content is here, right...

![image](https://cloud.githubusercontent.com/assets/25212/16566815/d9db013a-41cc-11e6-9429-b248164515d7.png)

Also, any special instructions for structure, direction, or flow to the new diagram?

**Comment by samanthaburton** [comment]
Oh no problem, I don't think I gave specific enough context. Sorry about that!

Yep, that's it - and you can use the paragraphs above it for framing, if need be. Would love your guidance on structure/flow of it, it's framed as "what --> why --> how" but I'm open to creative interpretations of how to show that visually.

Let me know if there's anything else I can do to help! Thanks so much.

**Comment by samanthaburton** [comment]
Ok @flukeout! 

A few more thoughts, from a more thorough look and a quick chat with Mark. Overall, looking GREAT - hugely appreciate all the time and energy you've put into making this happen so quickly.

**color scheme**
Mark asks that we prioritize black & white/grey-scale graphics, given that some of the places these will appear won't be in line with any colors we choose (eg. the wiki). Color is great to have too, but should be P2.

**MLN audiences & scale to depth**: these look awesome! Mark flagged that we're likely to want to update the people showcased in the audiences graphic at some point, but that's an FYI rather than something to worry about now.

**MLN structure & Advocacy Engine graphics**: we have new text for beneath each of these headings, but I think it may be too long for the graphics. If that's the case, they'll need to be revised with input from advocacy & MLN, so not in time for this week. I've provided the text below, if you'd like to play around with it - but if it's too long or too much trouble to make it work, just skip it & let me know and I'll work with the teams to shorten it & we can update the graphics later. 

**Advocacy Engine**
- change "**Campaigning (Short & Long Term)**" to "**Campaigns**"
- change "**world class infrastructure and networks**" to "**Infrastructure and Networks**"

_below are optional_
- change all text **below** "campaigns" to "Our campaigns amplify the Mozilla community’s collective voice, in order to address the issues we believe must be tackled in the current era to build the open Internet we want."
- change all text **below** "online" to "The pulse of the movement to protect the open Internet naturally lives on the web. We nurture a strong online community with a bias toward action, and drive mass digital mobilization behind our campaigns."
- change all text **below** "media" to "We tell creative, compelling stories that bring the biggest challenges and opportunities facing the open Internet to life, and into the mainstream."
- change all text **below** "field" to "Through the Internet Policy & Advocacy hub in the Mozilla Leadership Network, we connect, support and amplify the work of technologists, policy wonks, artists and activists committed to helping shape and drive Mozilla’s campaigns."
- change all text **below** "infrastructure and networks" to "The foundation that supports and drives our advocacy work by bringing together awesome people, organizations and technology to fuel our campaigns and the wider movement."

**MLN structure**
_below are optional_
- change all text **below** "strategic partnerships" to "We initiate and grow partnerships that enable Mozilla, our community and our allies to maximize their impact."
- change all text **below** "convening" to "We bring members of the Mozilla Leadership Network together, to learn from one another, exchange ideas and join forces. To support these connections, we design and facilitate a wide range of purpose-built spaces and events, both face-to-face and online."
- change all text **below** "learning" to "We provide leaders opportunities to up-level the skills they need to ensure the next wave of access, inclusion and opportunity online."
- change all text **below** "membership" to "Members of the Mozilla Leadership Network come from a wide range of career and life experience. Members join because they share Mozilla’s vision, and stay because of the strong, diverse community and unique professional development opportunities that membership provides."
- change all text **below** "production" to "The engine underpinning the Mozilla Leadership Network. We prototype, build and test the systems and infrastructure (tools, design, engineering) needed to support and scale the network and its members who learn and grow with us."

**Comment by flukeout** [comment]
@samanthaburton I've made the requested changes. Updated graphics are available here...

Okay here is the latest version of each diagram...

* [Dark days of the internet](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_dark-days.png)
* [MLN audiences](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mln-audiences.png)
* [MLN structure](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mln.png)
* [Mozilla Advocacy Engine](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mozilla-advocacy-engine.png)
* [Scale to Depth](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_scale-to-depth.png)

...these are the same links as above.

For the optional changes, I'd rather wait until the copy is finalized if that's OK with you. Let me know when that is and I'll update.

**Comment by samanthaburton** [comment]
These look great, @flukeout - thank you!

Totally cool on leaving the optional text out, until changes are finalized.

I noticed a couple more small things, then I think we're good to go -

1) Can we change the title of the first graphic from "dark days of the Internet" to "Mozilla Foundation Strategy"
2) Get rid of the hyphens mid-word in the following:
- Advocacy engine: "mobilization" and "communications"
- MLN structure: "incentives"
- Strategy diagram: "Leadership" under "How"

And that's it! Once that's done, I'll update them in the 1.0 document as well. Thanks again!

**Comment by flukeout** [comment]
Updated with latest changes...
- [Mozilla Foundation Strategy](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mozilla-foundation-strategy.png)
- [MLN audiences](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mln-audiences.png)
- [MLN structure](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mln.png)
- [Mozilla Advocacy Engine](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_mozilla-advocacy-engine.png)
- [Scale to Depth](https://dl.dropboxusercontent.com/u/109902/strategy-diagrams/strategy-diagrams_scale-to-depth.png)

**Comment by KevZawacki** [comment]
👏
